services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: climb-api
    command: flask run --host=0.0.0.0 --reload
    ports:
      - 5000:5000
    volumes:
      - ../backend:/app
  frontend:
    build:
      context: ../frontend
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ../frontend:/project
      - /project/node_modules
  postgres:
    image: postgres
    container_name: postgres-keycloak
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - type: "volume"
        source: keycloak-flask-db-data
        target: /var/lib/postgresql/data
  keycloak:
    depends_on:
      - postgres
    image: quay.io/keycloak/keycloak:11.0.0
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_ADDR: postgres
    volumes:
      - type: "volume"
        source: keycloak-flask-data
        target: /opt/jboss/keycloak/standalone/data
volumes:
  keycloak-flask-db-data:
  keycloak-flask-data: