services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: climb-api
    command: flask run --host=0.0.0.0 --reload
    environment:
      - MONGO_URI=${MONGO_URI}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - KEYCLOAK_ADMIN_NAME=${ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - mongo
    ports:
      - 5000:5000
    volumes:
      - ../backend:/app
  frontend:
    build:
      context: ../frontend
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ../frontend:/project
      - /project/node_modules
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  postgres:
    image: postgres
    container_name: postgres-keycloak
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_LOG_LEVEL: ERRORbash
    volumes:
      - type: "volume"
        source: keycloak-flask-db-data
        target: /var/lib/postgresql/data
  keycloak:
    depends_on:
      - postgres
    image: quay.io/keycloak/keycloak:11.0.0
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: ${ADMIN_USERNAME}
      KEYCLOAK_PASSWORD: ${ADMIN_PASSWORD}
      KEYCLOAK_LOGLEVEL: ERROR
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_ADDR: postgres
    volumes:
      - type: "volume"
        source: keycloak-flask-data
        target: /opt/jboss/keycloak/standalone/data
      - ../keycloak/login.css:/opt/jboss/keycloak/themes/keycloak/login/resources/css/login.css
volumes:
  keycloak-flask-db-data:
  keycloak-flask-data:
  mongo-data: